config/routes.rb
Rails.application.routes.draw do

  resources :articles, only: [:index, :new, :create, :edit, :update]

  root 'articles#index'

  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

end

app/models/article.rb
class Article < ActiveRecord::Base
  translates :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale
 
  def set_locale
    if cookies[:internalization_locale] && I18n.available_locales.include?(cookies[:internalization_locale].to_sym)
      l = cookies[:internalization_locale].to_sym
    else
      l = I18n.default_locale
      cookies.permanent[:internalization_locale] = l
    end
    I18n.locale = l
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.order('created_at DESC')
  end
 
  def new
    @article = Article.new
  end
 
  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:success] = t('forms.messages.success')
      redirect_to articles_path
    else
      render 'new'
    end
  end
 
  def edit
    @article = Article.find(params[:id])
  end
 
  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(article_params)
      flash[:success] = t('forms.messages.success')
      redirect_to articles_path
    else
      render 'edit'
    end
  end
 
  private
 
  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def change_locale
    l = params[:locale].to_s.strip.to_sym
    l = I18n.default_locale unless I18n.available_locales.include?(l)
    cookies.permanent[:internalization_locale] = l
    redirect_to request.referer || root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_article.html.erb
<h2><%= article.title %></h2>
 
<small class="text-muted"><%= l(article.created_at, format: '%-d %B %Y %H:%M:%S') %></small>
 
<p><%= article.body %></p>
 
<p><%= link_to t('forms.buttons.edit'), edit_article_path(article), class: 'btn btn-default' %></p>
<hr/>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', required: true %>
  </div>
 
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 3, class: 'form-control', required: true %>
  </div>
 
  <%= f.submit t('forms.buttons.submit'), class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/articles/edit.html.erb
<% content_for(:page_header) {t('.title')} %>
 
<%= render 'form' %>

app/views/articles/index.html.erb
<% content_for(:page_header) {t('.title')} %>

<small><%= t('.count', :count => @articles.length) %></small>

<%= render @articles %>

app/views/articles/new.html.erb
<% content_for(:page_header) {t('.title')} %>
 
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Internalization</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <%= link_to 'I18n', root_path, class: 'navbar-brand' %>
      </div>
 
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to t('menu.new_article'), new_article_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button">
            <%= t('menu.languages.lang') %>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to t('menu.languages.es'), change_locale_path(:es) %></li>
            <li><%= link_to t('menu.languages.ca'), change_locale_path(:ca) %></li>
            <li><%= link_to t('menu.languages.en'), change_locale_path(:en) %></li>
          </ul>
        </li>
      </ul>

    </div>
  </div>
 
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>
 
    <div class="page-header">
      <h1><%= yield :page_header %></h1>
    </div>
 
    <%= yield %>
  </div>
</body>
</html>